### ISSUE TITLE
Describe TMD recreation with Ansible script

### ISSUE THREAD

**Issue by brane007** [elixir-europe-training/Training-Metrics-Database#35] opened 2024-03-01 13:33 UTC
**Create Ansible script that will allow complete recreation of TMD database and Django system on existing or new server**

As a Node System Administrator, I want to recreate TMD, so that can create duplicate, backup or new instance of TMD.

**Describe alternatives you've considered**

**Is your feature request related to a problem? Please describe.**

**Additional context**

**Comment by mihai-sysbio** [comment] 2024-03-02 06:38
Interesting idea. What does "recreate TMD" mean? In essence, each Node owns their data, so this duplication/backup is a bit tricky.
Could you also provide a bit more context into why specifically an Ansible script? I'm asking to understand how this need captures the expectations of (many) Nodes, and the value it would provide over the very easy to follow [Developer documentation](https://github.com/elixir-europe-training/Training-Metrics-Database/wiki/Developer-documentation).

**Comment by pdmnyberg** [comment] 2024-03-04 08:12
I think Brane might have some more detail in regards of the need from a Node System Administrators perspective but for me as a developer I feel like it is valuable to have ansbile or something similar as a documentation of the expected production system. Since currently the runtime environment is not completely described in the repo. I think this is good to have if we are expected to be able to test the complete set of possible issues.

**Comment by pdmnyberg** [comment] 2024-11-22 10:21
I think we can close this as a non issue at this point. It is mostly relevant for deployment purposes and it is not completely relevant to TMD specifically. Let's just rely on docker and make sure it works and leave the scope of the proxy layer to the OPS. The problems caused by not knowing the setup is rare enough to ignore I think.

**Closed by pdmnyberg** 2024-11-22 10:21 UTC
Labels: enhancement
